### ISSUE TITLE
Regarding the panorama ids

### ISSUE THREAD

**Issue by howard50b** [deepmind/streetlearn#1]
Hi, 

First of all, thanks for releasing this environment and the awesome dataset! 

I'm wondering how I can get the list of all panorama ids?

Thanks!

**Comment by piotrmirowski** [comment]
Hello Howard,

Thanks for using the StreetLearn dataset!
The simplest way to get the list of paranorama IDs is to query the StreetLearn environment graph property, which returns a key value table of:
* keys that are pano ids of the graph nodes,
* and values are lists of pano ids directly connected to that node

For instance, in the script [human_agent.py](https://github.com/deepmind/streetlearn/blob/master/streetlearn/python/human_agent/human_agent.py), you can insert the following code after initialising and resetting the environment:
```
  env = streetlearn.StreetLearn(FLAGS.dataset_path, config, game)
  env.reset()
  for pano_id in env.graph:
    print(pano_id)
```

Hope this helps,

Best wishes,
Piotr

**Comment by howard50b** [comment]
Thanks! Unfortunately, I haven't been able to successfully set up the environment. I'll open up another issue for the error I got. But this is helpful!
