### ISSUE TITLE
opencv errors in bazel build

### ISSUE THREAD

**Issue by jameskilbride** [deepmind/streetlearn#10]
Having completed all of these processes specified in the setup I attempt to run bazel(downgraded to bazel 0.24 since 0.29 fails). and get the following error(Run on Ubuntu under Windows Subsystem for Linux): 

ERROR: /home/james/streetlearn/streetlearn/engine/BUILD:148:1: C++ compilation of rule '//streetlearn/engine:pano_projection' failed (Exit 1) process-wrapper failed: error executing command
  (cd /home/james/.cache/bazel/_bazel_james/997cc6ed3f0601f045ec4f5e6b23fe04/sandbox/processwrapper-sandbox/129/execroot/org_deepmind_streetlearn && \
  exec env - \
    PATH='/home/james/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc:/mnt/c/Program Files/Microsoft MPI/Bin/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/Common Files/Pleora/eBUS SDK:/mnt/c/Program Files/Common Files/Pleora/eBUS SDK:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/Git LFS:/mnt/c/Program Files/dotnet/:/mnt/c/Users/JamesKilbride/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/JamesKilbride/AppData/Local/GitHubDesktop/bin:/snap/bin:/home/james/bin' \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/james/.cache/bazel/_bazel_james/install/7da6a92c096ada842b8d48c251312343/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/streetlearn/engine/_objs/pano_projection/pano_projection.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/streetlearn/engine/_objs/pano_projection/pano_projection.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/k8-fastbuild/genfiles -iquote bazel-out/k8-fastbuild/bin -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/genfiles/external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -iquote external/opencv -iquote bazel-out/k8-fastbuild/genfiles/external/opencv -iquote bazel-out/k8-fastbuild/bin/external/opencv -isystem external/opencv/include -isystem bazel-out/k8-fastbuild/genfiles/external/opencv/include -isystem bazel-out/k8-fastbuild/bin/external/opencv/include -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c streetlearn/engine/pano_projection.cc -o bazel-out/k8-fastbuild/bin/streetlearn/engine/_objs/pano_projection/pano_projection.pic.o)
streetlearn/engine/pano_projection.cc:23:10: fatal error: opencv2/calib3d/calib3d.hpp: No such file or directory
 #include <opencv2/calib3d/calib3d.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jameskilbride** [comment]
This happened when running this command:  bazel build streetlearn/python/ui:all --sandbox_debug

**Comment by femarcos** [comment]
how did you solve that?
