### ISSUE TITLE
Access panorama information directly

### ISSUE THREAD

**Issue by cazhang** [deepmind/streetlearn#11]
The dataset is in form of .ldb format. Is there a way to access the panorama info using Python?
eg. return the label for a given panorama via string id?

**Comment by piotrmirowski** [comment]
Hello cazhang, the panoramas are stored in the levelDB files as protobufs in the following format:
https://github.com/deepmind/streetlearn/blob/master/streetlearn/proto/streetlearn.proto

There is a currently way for accessing all metadata from each panorama in the Python environment code, by requesting observation field `metadata`:
https://github.com/deepmind/streetlearn/blob/master/streetlearn/python/environment/observations.py#L196

For an example of how to request and print an observation for a list of pano IDs, in a simple Python executable:
https://github.com/deepmind/streetlearn/blob/master/streetlearn/python/ui/scan_agent.py

**Comment by piotrmirowski** [comment]
We are also going to add this data, in text format, as part of the upcoming dataset update (on http://streetlearn.cc/dataset).

**Comment by cazhang** [comment]
> We are also going to add this data, in text format, as part of the upcoming dataset update (on http://streetlearn.cc/dataset).

any update on this?

**Comment by piotrmirowski** [comment]
The metadata on the nodes (individual pano IDs, lat and long coordinates, angles of the camera system) and the links between nodes are now provided in the dataset that we release at [http://streetlearn.cc/dataset](http://streetlearn.cc/dataset).
