### ISSUE TITLE
Error when installing CLIF

### ISSUE THREAD

**Issue by howard50b** [deepmind/streetlearn#2]
Hi, I'm trying to follow the steps to install the environment. 

However, when executing to the line `"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" clif-matcher clif_python_utils_proto_util` in `INSTALL.sh` it shows the error `ImportError: No module named pyparsing`. I've pip installed pyparsing as instructed but this still occurs with or without using ninja. 

Would be great if you can help me with this. Thanks a lot!

**Comment by bhandras** [comment]
Hi Howard,
Thank you for reporting this. May I ask you what OS do you use? Also what is your Python version? Did you follow the prerequisite steps detailed in: https://github.com/google/clif#prerequisites ?

**Comment by 1576012404** [comment]
this problem occurs to me ,too.i am in anaconda environment,can it be in anaconda environment?

**Comment by bhandras** [comment]
Hi! Unfortunately we don't currently support anaconda. Please let me know if you need any help with the provided instructions.
