### ISSUE TITLE
Error running streetlearn

### ISSUE THREAD

**Issue by mforloines** [deepmind/streetlearn#3]
I have installed the program and am trying to run it, but when trying to run it via this line of code: 

> bazel run streetlearn/python/ui:human_agent -- --dataset_path=/home/martha/dataset/manhattan/

I get this error 

> "TypeError: coercing to Unicode: need string or buffer, NoneType found" 

I am using a virtualbox Ubuntu 18.04 desktop. There were no errors during install. Any help is appreciated.

**Comment by bhandras** [comment]
Hi,

Thank you for reporting, this is now fixed (in revision 0f5fbd5ac80a09c8f045e47b6f5100e2be15dafd).
