### ISSUE TITLE
Bazel version incompatibility

### ISSUE THREAD

**Issue by mweiss17** [deepmind/streetlearn#9]
Hello,
I believe that this repository's build files are not compatible with later versions of Bazel. I attempted the build process with Bazel 0.29.0 (currently the latest), and received many errors. When I reverted Bazel to version 0.24.0, the build process worked fine. Please add a note about the supported versions Bazel, or update the buildscripts. 
Thanks!
Martin

**Comment by jameskilbride** [comment]
Can confirm I had the same issues. Downgrade to 0.24.0 had it's own issue(see the open cv file not found issue) but at least it did attempt a build.

**Comment by piotrmirowski** [comment]
I updated the README.md file with the Bazel version that works (0.24.0).
